# ASSIGNMENT NO:- 2

Q-1)What will be the output after executing the following codes? Do not take the help of compiler
x=(0,8,9,67,45,9,0)
y=slice(1,-2)
x[y]

In [1]:
#(8, 9, 67, 45)

(8, 9, 67, 45)

Q-2)The method used to increase the length of the list by number of elements in its argument.
 a)add ()
 b)insert ()
 c)extend ()
 d)pop ()

In [ ]:
#b) insert

Q-3) ADD two sets
x={1,7,5,4}
y={8,9,"esh"}

In [ ]:
x.union(y)

TypeError: unhashable type: 'set'

Q-4) Find out which of the following code does not work on a tuple
 x+y
 sum(x)
 y[3] = 45
 len(y)

In [ ]:
#c)y[3]=45

Q-5) Which of the following is not a valid syntax for creating a Set ‘M’ in Python?
 a)M = set ([11,12,12,13,14,15])
 b)M = {11,12,13,14}
 c)M = set ([11,12],[13,14],[14,15])
 d)M = set ((11,12,13,14))

In [ ]:
#c

Q-6)Which of the following command returns the set of all elements from both sets, a and b
a={1,4,6,7,6,3}
b={5,8,9,0,5,3,4}

In [ ]:
a.union(b)
a

Q-7)For dictionary d = {"plum ":0.66, "pears ":1.25,"oranges ":0.50, "apple":0.75 }, 
write a code to correctly update the price of oranges to 0.90?

In [12]:
d = {"plum ":0.66, "pears ":1.25,"oranges ":0.50, "apple":0.75 }
e={"oranges":0.90}
d.update(e)
d

{'apple': 0.75, 'oranges': 0.9, 'oranges ': 0.5, 'pears ': 1.25, 'plum ': 0.66}

Q-8)What will be the output,do yourself without taking the help of compiler? 
c={}
c[1]=12
c["1"]=12
c[1]+=1

In [ ]:
{1: 13, '1': 12}

Q-9)Which of the following is not possible in sequence datatypes?
 a)Create a tuple inside a set
 b)Create a list inside a set
 c)Create a list inside a tuple
 d)Create a set inside a list

In [17]:
#b)

Q-10)Variable ‘a’ is defined as
       a = "gOOd moRning"
 write a code to convert ‘a’ from ‘gOOd moRning’ to ‘Good Morning’ is:-

Q-11) Create a list called “Stationery” which encompasses all the below variables

      Product = ['Pencil', 'Pen', 'Eraser', 'Pencil Box', 'Scale']
      Price= [5, 10, 2, 20, 12]  
      Brand = ['Camlin', 'Rotomac', 'Nataraj', 'Camel', 'Apsara']

In [19]:
Product = ['Pencil', 'Pen', 'Eraser', 'Pencil Box', 'Scale']
Price= [5, 10, 2, 20, 12]  
Brand = ['Camlin', 'Rotomac', 'Nataraj', 'Camel', 'Apsara']
stationery=[]
stationery.append(Product)
stationery.append(Price)
stationery.append(Brand)
stationery

[['Pencil', 'Pen', 'Eraser', 'Pencil Box', 'Scale'],
 [5, 10, 2, 20, 12],
 ['Camlin', 'Rotomac', 'Nataraj', 'Camel', 'Apsara']]

Q-12)write a code to add “Notebook” as the first element inside the first level of the list “Stationery” is:-

In [ ]:
stationery[1][1]=

Q-13) write a code to replace the element of Brand, “Camel” with “Camlin” inside the list is:-

In [ ]:
for i,j in enumerate(Brand):
    print(i,j)

0 Camlin
1 Camel
2 Camel
3 Rotomac
4 Nataraj
5 Camel
6 Apsara
7 Camel

In [ ]:
Brand

['Camlin',
 'Camlin',
 'Camlin',
 'Rotomac',
 'Nataraj',
 'Camlin',
 'Apsara',
 'Camlin']

Q-14) The list "Months" is defined as:-

       Months = ['Jan', 'Mar', 'June', 'Aug', 'June', 'Feb', 'Nov', 'Dec', 'June', 'Apr', 'May',     'June']

       Write a code which returns the number of occurrences of ‘June’?

In [22]:
Months = ['Jan', 'Mar', 'June', 'Aug', 'June', 'Feb', 'Nov', 'Dec', 'June', 'Apr', 'May','June']
x='June'
count=0
for i in Months:
  if i == x:
    count=count+1
print("Occurence of June:",count)

Occurence of June: 4

Q-15) Given the variables:**

planet = "Earth"
diameter = 12742
** Use .format() to print the following string: **

The diameter of Earth is 12742 kilometers.

In [25]:
print("The diameter of {planet} is {diameter} kilometers".format(planet="Earth",diameter=12742))

The diameter of Earth is 12742 kilometers

Q-16)Given this nested list, use indexing to grab the word "hello"
lst = [1,2,[3,4],[5,[100,200,['hello',1000]],23,11],1,7]

Q-17) Given this nested dictionary grab the word "hello".
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d["k1"][3]["tricky"][3]

{'target': [1, 2, 3, 'hello']}

Q-18) convert this string into a list but output of list should be in words not in alphabets.
s = "Hi there Sam!"

In [ ]:
s = "Hi there Sam!"

a=list(s)
a

['H', 'i', ' ', 't', 'h', 'e', 'r', 'e', ' ', 'S', 'a', 'm', '!']

Q-19) Write a code to extract the number at the end of the line below and also Convert the extracted value to a floating point number.

text = "X-DSPAM-Confidence:    0.8475";

Q-20) a=(1,5,6,7,8,"datascience")

replace "datascience" to "deeplearning"