**1) Write a Python function to calculate the factorial of a number**

In [ ]:
def fact(x):
  num=1
  for i in range(1,x+1):
    num=num*i
  print(num)

fact(7)

5040

**2) Write a Python function to check whether a number is in a given range. Hint: specify a range first
in your code then check whether that number is in your range or not**

In [6]:
def num():
  n=int(input("Enter a number:"))
  for i in range(1,101):
    if n//i==1 and n%i==0:
      print("Yes , this number exists within 1-100 range ")
      break
  else:
    print("No, it doesnt exist within 1-100 range")
num()

Enter a number:102
No, it doesnt exist within 1-100 range

**3) Write a Python function to multiply all the numbers given in the input. E.g.: Input numbers 1,3,5.
Output: 15**

In [11]:
def mult():
  y=1
  x=str(input("Enter a number:"))
  for i in x:
    y=y*int(i)
  print(y)
mult()

Enter a number:135
15

**4) Output of the code**

In [ ]:
Ans : 6

**5) Output of the code**

In [ ]:
dcba4321